/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeScoreboard */

#ifndef _Included_NativeScoreboard
#define _Included_NativeScoreboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      NativeScoreboard
 * Method:     calc
 * Signature:  (III)I
 */
JNIEXPORT jint JNICALL Java_NativeScoreboard_calc
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
